/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.BookTicketUserController;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.Movie;
import model.Showtime;
import model.ShowtimeInfor;

/**
 *
 * @author ADMIN
 */
public class BookTicketUserPanel extends javax.swing.JPanel {

    private String idPhimtoSuatChieu;
    ArrayList<JButton> danhSachGhe = new ArrayList<>();
    private Showtime clickedShowTime;
    List<JButton> selectedButton = new ArrayList<>();
    Map<String, String> suatChieuToPhongMap = new HashMap<>();
    private boolean isComboBoxReady = false;
    private double giaVeHienTai = 0;
    private List<String> list = new ArrayList<>();
    private Account account;

    private BookTicketUserController bookTicketUserController;
    private Movie movie;

    public BookTicketUserPanel() {
        initComponents();
        taoGhe();
        bookTicketUserController = new BookTicketUserController();
        hienThiSuatChieu(idPhimtoSuatChieu);
        TenSuatChieu.setText("");
        CountSeat.setText("");
        PriceSeatLabel.setText("");
        Tongtien.setText("");

    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
        idPhimtoSuatChieu = movie.getId();
        FilmName.setText(movie.getTitle());
        FilmName1.setText(movie.getTitle());
        TenSuatChieu.setText("");
        hienThiSuatChieu(idPhimtoSuatChieu);
    }

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                // Tạo JFrame làm container chính
                javax.swing.JFrame frame = new javax.swing.JFrame("Đặt Vé Xem Phim");

                // Cấu hình JFrame
                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
//            frame.setPreferredSize(new java.awt.Dimension(1400, 700));

                // Thêm BookTicketUserPanel vào JFrame
                frame.getContentPane().add(new BookTicketUserPanel());

                // Hiển thị JFrame
                frame.pack();
                frame.setLocationRelativeTo(null); // Hiển thị giữa màn hình
                frame.setVisible(true);
            }
        });
    }

    public void reload() {
        for (JButton ghe : danhSachGhe) {
            ghe.setBackground(UIManager.getColor("Button.background")); // Màu mặc định
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TenPC = new javax.swing.JLabel();
        SEAT = new javax.swing.JPanel();
        ChuThich = new javax.swing.JPanel();
        DaDat = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        DangChon = new javax.swing.JPanel();
        Trong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Film = new javax.swing.JLabel();
        FilmName = new javax.swing.JLabel();
        XuatChieu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        FilmName1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TenSuatChieu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Count = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        CountSeat = new javax.swing.JLabel();
        PriceSeatLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ShowTime = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Tongtien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DatVe = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1400, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1400, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 600));

        TenPC.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        TenPC.setText("Phòng chiếu 01");

        SEAT.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout SEATLayout = new javax.swing.GroupLayout(SEAT);
        SEAT.setLayout(SEATLayout);
        SEATLayout.setHorizontalGroup(
            SEATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SEATLayout.setVerticalGroup(
            SEATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        ChuThich.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DaDat.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout DaDatLayout = new javax.swing.GroupLayout(DaDat);
        DaDat.setLayout(DaDatLayout);
        DaDatLayout.setHorizontalGroup(
            DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DaDatLayout.setVerticalGroup(
            DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ghế đã bán");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        DangChon.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout DangChonLayout = new javax.swing.GroupLayout(DangChon);
        DangChon.setLayout(DangChonLayout);
        DangChonLayout.setHorizontalGroup(
            DangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        DangChonLayout.setVerticalGroup(
            DangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        Trong.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout TrongLayout = new javax.swing.GroupLayout(Trong);
        Trong.setLayout(TrongLayout);
        TrongLayout.setHorizontalGroup(
            TrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        TrongLayout.setVerticalGroup(
            TrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ghế trống");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ghế đang chọn");

        javax.swing.GroupLayout ChuThichLayout = new javax.swing.GroupLayout(ChuThich);
        ChuThich.setLayout(ChuThichLayout);
        ChuThichLayout.setHorizontalGroup(
            ChuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChuThichLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Trong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DaDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ChuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(45, 45, 45)
                .addComponent(DangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ChuThichLayout.setVerticalGroup(
            ChuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChuThichLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ChuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DaDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Trong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29))
            .addGroup(ChuThichLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ChuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(DangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SCREEN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel4)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ChuThich, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TenPC)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SEAT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(TenPC)
                .addGap(18, 18, 18)
                .addComponent(ChuThich, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(SEAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel4.setPreferredSize(new java.awt.Dimension(750, 600));

        Film.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Film.setText("PHIM: ");

        FilmName.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        FilmName.setText("Tên phim");

        XuatChieu.setMaximumSize(new java.awt.Dimension(650, 300));
        XuatChieu.setPreferredSize(new java.awt.Dimension(650, 300));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Phim: ");

        FilmName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Suất chiếu: ");

        TenSuatChieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Count.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Count.setText("Số lượng:");

        Price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Price.setText("Giá tiền:");

        CountSeat.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        PriceSeatLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        javax.swing.GroupLayout XuatChieuLayout = new javax.swing.GroupLayout(XuatChieu);
        XuatChieu.setLayout(XuatChieuLayout);
        XuatChieuLayout.setHorizontalGroup(
            XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XuatChieuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(XuatChieuLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)
                        .addComponent(TenSuatChieu))
                    .addGroup(XuatChieuLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(74, 74, 74)
                        .addComponent(FilmName1))
                    .addGroup(XuatChieuLayout.createSequentialGroup()
                        .addComponent(Price)
                        .addGap(59, 59, 59)
                        .addComponent(PriceSeatLabel))
                    .addGroup(XuatChieuLayout.createSequentialGroup()
                        .addComponent(Count)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(CountSeat)))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        XuatChieuLayout.setVerticalGroup(
            XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XuatChieuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(FilmName1))
                .addGap(18, 18, 18)
                .addGroup(XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TenSuatChieu))
                .addGroup(XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(XuatChieuLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8))
                    .addGroup(XuatChieuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Count)
                            .addComponent(CountSeat))))
                .addGap(23, 23, 23)
                .addGroup(XuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price)
                    .addComponent(PriceSeatLabel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Chọn suất chiếu:");

        ShowTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ShowTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowTimeMouseClicked(evt);
            }
        });
        ShowTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTimeActionPerformed(evt);
            }
        });

        jPanel6.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(650, 100));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tổng tiền: ");

        Tongtien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(Tongtien)
                .addGap(92, 92, 92))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Tongtien))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tổng thanh toán:");

        DatVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DatVe.setText("Thanh toán");
        DatVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatVeMouseClicked(evt);
            }
        });
        DatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(XuatChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(ShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(507, 507, 507)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(DatVe)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Film)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FilmName)
                .addGap(262, 262, 262))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Film)
                    .addComponent(FilmName))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(XuatChieu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatVe)
                .addGap(59, 59, 59))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void DatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatVeActionPerformed
        if (clickedShowTime == null) {
            JOptionPane.showMessageDialog(
             null,
             "❌ Vui lòng chọn suất chiếu trước khi đặt vé!",
             "Lỗi",
             JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        boolean hasSelectedSeat = false;
        for (JButton ghe : danhSachGhe) {
            if (ghe.getBackground().equals(Color.GREEN)) {
                hasSelectedSeat = true;
                break;
            }
        }
        if (!hasSelectedSeat) {
            JOptionPane.showMessageDialog(
             null,
             "Vui lòng chọn ít nhất một ghế trước khi đặt vé!",
             "Cảnh báo",
             JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
         null,
         "Bạn có chắc muốn đặt các ghế đã chọn không?",
         "Xác nhận đặt vé",
         JOptionPane.YES_NO_OPTION,
         JOptionPane.QUESTION_MESSAGE
        );
        // Nếu người dùng hủy bỏ, thoát luôn
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        list.clear();
        // Duyệt qua danh sách ghế và đặt vé
        for (JButton ghe : danhSachGhe) {

            if (ghe.getBackground().equals(Color.GREEN)) {
                String seatName = ghe.getName();
                ghe.setBackground(Color.RED); // Đánh dấu ghế đã đặt

                String roomId = clickedShowTime.getScreenRoomId();
                String seatId = bookTicketUserController.getSeatId(seatName, roomId);
                String showTimeId = clickedShowTime.getId();

                String maVe = "VE" + UUID.randomUUID().toString().substring(0, 6).toUpperCase();
                try {
                    boolean result = bookTicketUserController.datVe(maVe, showTimeId, seatId, idPhimtoSuatChieu, account.getId());

                    if (!result) {
                        JOptionPane.showMessageDialog(
                         null,
                         "❌ Đặt vé thất bại cho ghế " + seatName + ".",
                         "Lỗi",
                         JOptionPane.ERROR_MESSAGE
                        );
                        ghe.setBackground(Color.GREEN); // Khôi phục màu nếu lỗi
                    } else {
                        list.add(maVe);
                    }
                } catch (Exception e) {
                    ghe.setBackground(Color.GREEN); // Khôi phục nếu lỗi
                    JOptionPane.showMessageDialog(
                     null,
                     "💥 Lỗi khi kết nối hoặc truy vấn CSDL với ghế " + seatName + ":\n" + e.getMessage(),
                     "Lỗi CSDL",
                     JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        }
        int soluong = selectedButton.size();
        double tongTien = giaVeHienTai * soluong;
        String danhSachGhe = String.join(", ",
         selectedButton.stream()
          .map(JButton::getText)
          .toArray(String[]::new));
        String note = "Đã đặt " + soluong + " vé xem phim. Ghế: " + danhSachGhe;
        String maHD = "HD" + UUID.randomUUID().toString().substring(0, 6).toUpperCase();
        try {
            // 2. Đánh dấu ghế đã đặt (chỉ đổi màu)
            for (JButton ghe : selectedButton) {
                ghe.setBackground(Color.RED);
            }
            // 3. Tạo 1 hóa đơn duy nhất
            if (!bookTicketUserController.InsertHoaDon(maHD, account.getId(), tongTien, note)) {
                throw new Exception("Tạo hóa đơn thất bại");
            }
            JOptionPane.showMessageDialog(null, "Đặt vé thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            for (String maVe : list) {
                bookTicketUserController.InsertChiTietHoaDon(maHD, maVe);
            }
        } catch (Exception e) {
            // Khôi phục màu ghế nếu lỗi
            for (JButton ghe : selectedButton) {
                ghe.setBackground(Color.GREEN);
            }
            JOptionPane.showMessageDialog(null, "Lỗi: " + e.getMessage(), "Thất bại", JOptionPane.ERROR_MESSAGE);
        } finally {
            // 4. Reset giao diện
            selectedButton.clear();
            CountSeat.setText("0");
            PriceSeatLabel.setText("0đ");
            Tongtien.setText("0đ");
        }
    }//GEN-LAST:event_DatVeActionPerformed

    private void ShowTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTimeActionPerformed
        if (!isComboBoxReady) {
            return;
        }
        String suatChieuDuocChon = (String) ShowTime.getSelectedItem();
        if (suatChieuDuocChon != null && suatChieuToPhongMap.containsKey(suatChieuDuocChon)) {
            TenSuatChieu.setText(suatChieuDuocChon);
            String[] parts = suatChieuDuocChon.split(" - ");
            if (parts.length == 2) {
                String phongChieu = parts[1]; // phần "Phòng X"
                TenPC.setText(phongChieu);
            }
        }

        ArrayList<Showtime> list;
        try {
            int index = ShowTime.getSelectedIndex();

            if (index < 0) {
                return; //Không có mục nào được chọn
            }

            //Lấy danh sách suất chiếu từ db
            list = (ArrayList<Showtime>) bookTicketUserController.showShowTime(idPhimtoSuatChieu);

            //Lấy suất chiếu tương ứng với index
            Showtime item = list.get(index);
            clickedShowTime = item;
            giaVeHienTai = clickedShowTime.getTicketPrice();
            System.out.println(item.getId());

            //Lấy danh sách tên các ghế đã được đặt
            ArrayList<String> danhSachGheDaDat = bookTicketUserController.searchSeatNameFromsShowTime("Dadat", item.getId());
            if (danhSachGheDaDat == null) {
                danhSachGheDaDat = new ArrayList<>();
            }
            System.out.println(danhSachGheDaDat.toString());
            for (JButton ghe : danhSachGhe) {
                if (danhSachGheDaDat.indexOf(ghe.getText()) != -1) {
                    ghe.setBackground(Color.red);
                } else {
                    ghe.setBackground(UIManager.getColor("Button.background"));
                }
            }
        } catch (Exception e1) {
        }

        selectedButton.clear();
        CountSeat.setText("");
        PriceSeatLabel.setText("");
        Tongtien.setText("");

    }//GEN-LAST:event_ShowTimeActionPerformed

    private void ShowTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowTimeMouseClicked

    }//GEN-LAST:event_ShowTimeMouseClicked

    private void DatVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatVeMouseClicked

    }//GEN-LAST:event_DatVeMouseClicked

    private void hienThiSuatChieu(String tenPhim) {
        isComboBoxReady = false;
        List<ShowtimeInfor> danhSachSuatChieu = bookTicketUserController.getShowTime(tenPhim);

        ShowTime.removeAllItems();
        suatChieuToPhongMap.clear();

        for (ShowtimeInfor suat : danhSachSuatChieu) {
            String gioBatDau = suat.getStartTime() + " - " + suat.getName();
            ShowTime.addItem(gioBatDau);
            suatChieuToPhongMap.put(gioBatDau, suat.getName());
            TenPC.setText(danhSachSuatChieu.get(0).getName());
        }
        isComboBoxReady = true;
    }

    private void taoGhe() {
        SEAT.setLayout(new GridLayout(5, 8, 5, 5));
        SEAT.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        String[] hangGhe = {"A", "B", "C", "D", "E"};
        for (String hang : hangGhe) {
            for (int col = 1; col <= 8; col++) {
                String gheText = hang + col;
                JButton button = new JButton(gheText);
                button.setBackground(UIManager.getColor("Button.background"));
                button.setName(gheText);
                button.setBackground(UIManager.getColor("Button.background"));

                button.addActionListener(new ActionListener() {
                    @Override

                    public void actionPerformed(ActionEvent e) {
                        if (button.getBackground().equals(Color.RED)) {
                            return;
                        } else if (button.getBackground().equals(Color.GREEN)) {
                            button.setBackground(UIManager.getColor("Button.background"));
                            selectedButton.remove(button);
                        } else {
                            button.setBackground(Color.green);
                            selectedButton.add(button);
                        }

                        int soLuong = selectedButton.size();
                        double tongTien = giaVeHienTai * soLuong;

                        CountSeat.setText(String.valueOf(soLuong));
                        PriceSeatLabel.setText(String.format("%,.0f", tongTien) + "đ");
                        Tongtien.setText(String.format("%,.0f", tongTien) + "đ");
                    }
                });

                button.setFont(new Font("Arial", Font.BOLD, 12));
                SEAT.add(button);
                danhSachGhe.add(button);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChuThich;
    private javax.swing.JLabel Count;
    private javax.swing.JLabel CountSeat;
    private javax.swing.JPanel DaDat;
    private javax.swing.JPanel DangChon;
    private javax.swing.JButton DatVe;
    private javax.swing.JLabel Film;
    private javax.swing.JLabel FilmName;
    private javax.swing.JLabel FilmName1;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel PriceSeatLabel;
    private javax.swing.JPanel SEAT;
    private javax.swing.JComboBox<String> ShowTime;
    private javax.swing.JLabel TenPC;
    private javax.swing.JLabel TenSuatChieu;
    private javax.swing.JLabel Tongtien;
    private javax.swing.JPanel Trong;
    private javax.swing.JPanel XuatChieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
