/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.MovieTicketHistoryUserController;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Account;

/**
 *
 * @author ADMIN
 */
public class MovieTicketHistoryUser extends javax.swing.JPanel {

    private MovieTicketHistoryUserController movieTicketHistoryUserController;
    private Account account;

    /**
     * Creates new form MovieTicketHistoryUser
     */
    public MovieTicketHistoryUser() {
        movieTicketHistoryUserController = new MovieTicketHistoryUserController();
        initComponents();
        SearchjButton.addActionListener(e -> {
            String tenPhim = SearchName.getText().trim();
            String maTaiKhoan = account.getId();

            // Xóa dữ liệu cũ trong bảng
            DefaultTableModel model = (DefaultTableModel) jTableBill.getModel();
            model.setRowCount(0);

            // Gọi phương thức search() để tìm kiếm
            search(model, maTaiKhoan, tenPhim);
        });
        SwingUtilities.invokeLater(() -> {
            DefaultTableModel model = (DefaultTableModel) jTableBill.getModel();
            loadMovieTicketHistory(model, account.getId());
        });
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public void load() {
        DefaultTableModel model = (DefaultTableModel) jTableBill.getModel();
        loadMovieTicketHistory(model, account.getId());
    }

    public void loadMovieTicketHistory(DefaultTableModel table, String idTaiKhoan) {
        List<Object[]> invoiceData = movieTicketHistoryUserController.getInvoiceInfor(idTaiKhoan);
        table.setRowCount(0);
        if (invoiceData != null && !invoiceData.isEmpty()) {
            for (Object[] row : invoiceData) {
                // Định dạng lại dữ liệu nếu cần
                Object[] formattedRow = Arrays.copyOf(row, row.length);

                // Định dạng tiền tệ (giả sử cột tổng tiền là vị trí số 6)
                if (formattedRow.length > 6 && formattedRow[6] instanceof Number) {
                    formattedRow[6] = String.format("%,d VND", ((Number) formattedRow[6]).intValue());
                }

                table.addRow(formattedRow);
            }
        } else {
            // Hiển thị thông báo nếu không có dữ liệu
//        JOptionPane.showMessageDialog(null, 
//            "Không tìm thấy lịch sử vé cho suất chiếu này", 
//            "Thông báo", 
//            JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titles = new javax.swing.JLabel();
        SearchName = new javax.swing.JTextField();
        SearchjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBill = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1400, 700));

        Titles.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Titles.setText("LỊCH SỰ HÓA ĐƠN ĐẶT VÉ XEM PHIM");

        SearchjButton.setBackground(new java.awt.Color(153, 204, 255));
        SearchjButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchjButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchjButton.setText("Tìm kiếm");
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });

        jTableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên phim", "Ngày đặt vé", "Ngày chiếu", "Giờ chiếu", "Số ghế", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(jTableBill);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(Titles))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(SearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(SearchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Titles)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchName)
                    .addComponent(SearchjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void search(DefaultTableModel table, String maTaiKhoan, String tenPhim) {
        List<Object[]> ketQua = movieTicketHistoryUserController.timKiemHoaDonTheoPhim(maTaiKhoan, tenPhim);
        if (ketQua != null && !ketQua.isEmpty()) {
            for (Object[] row : ketQua) {
                Object[] formattedRow = Arrays.copyOf(row, row.length);
                if (formattedRow.length > 6 && formattedRow[6] instanceof Number) {
                    formattedRow[6] = String.format("%,d VND", ((Number) formattedRow[6]).intValue());
                }
                table.addRow(formattedRow);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Không tìm thấy lịch sử vé cho phim: " + tenPhim + "\nKiểm tra lại tên phim hoặc mã tài khoản.",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }


    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed

    }//GEN-LAST:event_SearchjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchName;
    private javax.swing.JButton SearchjButton;
    private javax.swing.JLabel Titles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBill;
    // End of variables declaration//GEN-END:variables

}
